tesst

diff --git a/.github/workflows/nextjs.yaml b/.github/workflows/nextjs.yaml
--- a/.github/workflows/nextjs.yaml
+++ b/.github/workflows/nextjs.yaml
@@ -29,9 +29,19 @@ jobs:
 
       - name: Set Environment Variables
         run: |
-          echo "PROJECT_ID=$(gcloud config get-value project)" >> $GITHUB_ENV
-          echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
+          PROJECT_ID=$(gcloud config get-value project)
+          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
+
+          if [[ -z "$PROJECT_ID" || -z "$REPO_NAME" ]]; then
+            echo "Error: PROJECT_ID or REPO_NAME is empty!" >&2
+            exit 1
+          fi
+
+          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
+          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
           echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
+          echo "GCR_REGISTRY=gcr.io/$PROJECT_ID" >> $GITHUB_ENV
+          echo "GCR_REPOSITORY=$REPO_NAME" >> $GITHUB_ENV
 
       - name: Ensure GCR Repository Exists
         run: |
@@ -48,12 +58,13 @@ jobs:
       - name: Build and Push Docker Image to GCR
         run: |
           echo "Building Docker image..."
-          docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .
-          
+          docker build -t $GCR_REGISTRY/$GCR_REPOSITORY:latest -t $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG .
+
           echo "Pushing Docker image to GCR..."
-          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG
+          docker push $GCR_REGISTRY/$GCR_REPOSITORY:latest
+          docker push $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG
 
       - name: Verify Image in GCR
         run: |
           echo "Checking if image exists in GCR..."
-          gcloud container images list-tags gcr.io/$PROJECT_ID/$REPO_NAME --format="table(digest, tags, timestamp.datetime)"
+          gcloud container images list-tags $GCR_REGISTRY/$GCR_REPOSITORY --format="table(digest, tags, timestamp.datetime)"
